name: Publish plugin to npm
on: [push, pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test:e2e-headless
      - run: npm run semantic-release